name: Renovate

on:
  push:
    branches: [test]
  schedule:
    # 每 15 分鐘執行一次
    - cron: '*/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.0
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
        env:
          LOG_LEVEL: 'debug'
